
[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
fileWatcherType = "none"
allowRunOnSave = false

[browser]
gatherUsageStats = false

[client]
caching = true
displayEnabled = true

[runner]
magicEnabled = true
installDependencies = true
