[server]
headless = true
port = 5000
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
fileWatcherType = "none"
allowRunOnSave = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "light"